### ISSUE TITLE
the bot doesnt reply anything 

### ISSUE THREAD

**Issue by mornflakes928** [danimart1991/jackett2telegram#1]
the bot doesnt reply anything but the status is executed successfully, i thought i fill wrong chat id and token, but after checking it, i fill the correct chat id and token, do you know what my problem is? you can see the code on fork

**Comment by danimart1991** [comment]
You need a Jackett instance running, and then copy any RSS Feed from Jackett and use it in the bot like:
_/add TrackerName RSSFeedUrl_

**Comment by danimart1991** [comment]
Anyway. 
The Token is all the id given you by BotFather: 12345678901:ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
The Chat Id (it seems that your chat id is a group) is the another id: -87654321

The groups have a '-' before the chatid. You need to enter it too.

On the other side. Your repo is public, so someone could use your bot data.

**Comment by mornflakes928** [comment]
![Screenshot_2021-02-03-00-03-12-18_74594bd74a0419242537a8d02ba17993](https://user-images.githubusercontent.com/77254405/106635345-4ec4be00-65b3-11eb-8413-1b2fe27cc23e.jpg)
ive tried to fill the chat id with my group chat id (-544963074) but i dont know why on that group the bot doesnt reply my /help command, so i use the bot chat id instead of group chat id (1657427162) but it still doesnt want to reply my /help command :(

**Comment by danimart1991** [comment]
Try to use the bot in a normal chat (no group). I don't try the bot in groups, so maybe is not prepared yet.

**Comment by danimart1991** [comment]
Hi @mornflakes928.

Was the issue fixed?

**Comment by danimart1991** [comment]
Bot tested in groups. Works fine.

Issue closed because of inactivity.
