### ISSUE TITLE
ERROR: Indexer not available due to some issue: RARBG

### ISSUE THREAD

**Issue by DarremMolko** [danimart1991/jackett2telegram#10]
Hola. He estado usando el bot desde hace unos días pero he tenido problemas usando el indexer de RARBG, cada tanto me aparece el error que he puesto en el título y el bot comienza a enviar muchas publicaciones repetidas (me fui a dormir y desperté con 1400 mensajes). Pensé que sería el delay (1 minuto), por lo que lo cambié a 5 minutos pero me siguió ocurriendo lo mismo. También uso TorrentGalaxy e YTS pero con estos no he tenido problemas. Debajo dejo captura del error:
![Screenshot_20220414-193801](https://user-images.githubusercontent.com/70179709/163490702-b75c7921-60fd-4208-84f5-8110f368a1d9.jpg)
![Screenshot_20220414-193956](https://user-images.githubusercontent.com/70179709/163490713-409b0244-51d2-49b2-b8dc-558b655a9cd4.jpg)

**Comment by danimart1991** [comment]
Buenas @DarremMolko 

Por lo que leo, parece que son problemas de timeout, tanto en la conexión con Telegram, como con los indexers. Esto puede ser debido a bloqueos de tu proveedor de internet, o directamente a una conexión poco estable. ¿Puedes revisar si estas son las razones?

También quiero indicarte que Rarbg suele tener bastantes problemas de conexión en España. Yo mismo suelo tener problemas para entrar y tengo que buscar distinto proxies que no siempre funcionan correctamente.

**Comment by DarremMolko** [comment]
Hola Dani. El bot lo tengo hospedado en un VPS basado en Alemania, no sé si eso tenga algo que ver, pero ya he tenido hospedados allí otros bots de Telegram sin problemas. Anoche recibí otro tipo de error, lo dejo aquí debajo:

```
root - ERROR - Indexer not available due to some issue: RARBG
Traceback (most recent call last):
File "./jackett2telegram.py", line 203, in rss_monitor
root = ElementTree.fromstring(response.content)
File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1349, in XML
parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 6, column 2

```
Pero si no estoy entendiendo mal el problema allí es con el feed. Luego de eso he optado por cambiar el delay a 1 hora y por el momento sin inconvenientes. 
Creo que si no hay nada que se pueda hacer puedes cerrar este issue.

**Comment by danimart1991** [comment]
Si. Es lo que te comento, problemas al traerse la información desde RARBG. En este último caso por ejemplo es que ha recibido algo que no sabe interpretar, vete a saber qué.

Por ahora poco puedo hacer al respecto. Cierro el issue y si por un casual encuentras algo más de info, no dudes en abrir de nuevo.
