### ISSUE TITLE
Blackhole directory

### ISSUE THREAD

**Issue by urtaevS** [danimart1991/jackett2telegram#12]
I've configure the blackhole directory in Jackett. And if i hit the button in Jackett, 
![Снимок экрана 2022-06-17 в 18 20 35](https://user-images.githubusercontent.com/66906118/174328541-86e3b461-bf6e-4277-a3b1-0473405374df.png)
everything work correct but when i doing this with the bot, nothing happens.

P.S. Installed as script.

**Comment by danimart1991** [comment]
Hi @urtaevS 

Does the log show any error or message?

**Comment by urtaevS** [comment]
Can you help me get the log?

**Comment by danimart1991** [comment]
> Can you help me get the log?

I assume you run something like `python3 jackett2telegram.py`. This gives you a log when is executed.

Anyway. _Jackett2Telegram_ leave the _backhole_ files in a folder called blackhole where the `jackett2telegram.py` file is. Could you check if there is a folder there?

**Comment by urtaevS** [comment]
Ok, I'll try it.
Blackhole path in Jackett ~/share/documents/Torrentz
Jackett2Telegram.py path ~/J2T/jackett2telegram.py

I've try change path to the j2t script and it's won't works.

**Comment by urtaevS** [comment]
Ok, I'll try it.
Blackhole path in Jackett ~/share/documents/Torrentz
Jackett2Telegram.py path ~/J2T/jackett2telegram.py


Oh! I find the blackhole directory in folder with script! Thank you!

Can I move it to the other path?

**Comment by danimart1991** [comment]
I think you could modify the Line 14 of the Script to point another folder path: https://github.com/danimart1991/jackett2telegram/blob/main/jackett2telegram.py#L14

But it could cause issues with permissions.
