### ISSUE TITLE
Magnet link

### ISSUE THREAD

**Issue by urtaevS** [danimart1991/jackett2telegram#14]
Can you please add a magnet link url to message? Is it possible?

**Comment by danimart1991** [comment]
Hello @urtaevS. Thanks for your comment.

I am sorry to tell you that it is not possible. I already tried to add the magnet links to the message in several ways, but I ran into several problems in its implementation.

- These links do not always come in the same way and in the same property in the different trackers that Jackett manages, this forces me to implement logic in the bot for each tracker, which would add complexity and maintenance that I cannot undertake.
- The magnet links are very long, this means that they do not fit into a single Telegram message and if I include it as a possible copy to clipboard button, the entire link would not fit on some devices, and on others it would simply fail.
