### ISSUE TITLE
ModuleNotFoundError: No module named 'telegram.utils'

### ISSUE THREAD

**Issue by bulletproof2k** [danimart1991/jackett2telegram#16]
```
D:\IDE\.py\jackett2telegram-main>python jackett2telegram.py
Traceback (most recent call last):
  File "D:\IDE\.py\jackett2telegram-main\jackett2telegram.py", line 11, in <module>
    from telegram.utils import helpers
ModuleNotFoundError: No module named 'telegram.utils'
```
I assume that you need to update the module `telegram-bot`.

**Comment by danimart1991** [comment]
Hello.

Maybe you are using the wrong `python-telegram-bot` version. `Jackett2Telegram` actually uses the version **13.15**.

**Comment by bulletproof2k** [comment]
python-telegram-bot>=20.0.0

**Comment by danimart1991** [comment]
You use the wrong version that the requirements.txt indicates for jackett2telegram. Maybe I update the version in the future. But actually, you need to use the version 13.15 or docker to avoid this.
