### ISSUE TITLE
Doesn't check anything v 1.15

### ISSUE THREAD

**Issue by urtaevS** [danimart1991/jackett2telegram#19]
After update on 1.15, it's won't check any rss. 
With version 1.11 all going well.

**Comment by danimart1991** [comment]
Hello @urtaevS 

What installation mode do you use?
Did you do a `/test` and/or `/list` commands to check health?

**Comment by urtaevS** [comment]
> Hello @urtaevS
> 
> What installation mode do you use? Did you do a `/test` and/or `/list` commands to check health?

Hi!
Docker installation.

`/test` and `/list` run without any errors and work as expected.

**Comment by urtaevS** [comment]
![Снимок экрана 2024-04-26 в 10 26 58](https://github.com/danimart1991/jackett2telegram/assets/66906118/facaed68-8af0-40b1-a85e-b055bfb5e94d)
It's this what you need?

**Comment by danimart1991** [comment]
v1.16 must resolve the issue.
