### ISSUE TITLE
RARBG

### ISSUE THREAD

**Issue by Xazmah** [danimart1991/jackett2telegram#2]
Using latest version "Jackett Version v0.17.1027" as of now

When sending a /test with RARBG RSS feed I get in logs Info Torznab search in RARBG for REMUX => Found 100 releases (from cache) but the bot not sending any response message, Same RSS feed work fine with other RSS bots

Also when I /add the RARBG RSS feed the status is ⚠️ all the time

**Comment by mohitjoshi155** [comment]
I am also facing the same issue...

**Comment by xavierxross** [comment]
https://da.gd/jackett2tg

**Comment by danimart1991** [comment]
Telegram only supports `http/http/tg` links, so trackers like _RARBG_ that only give magnet links can't obtain the `http://rarbg....torrent` URL. I fix this to only include the Link to the page where you could obtain the magnet. If Jackett updates these trackers to obtain the `.torrent`, then the bot will show the _Blackhole/.Torrent_ buttons.

**Comment by Xazmah** [comment]
@danimart1991 The link it provide now is rarbg.to/infohash/HASH instead of magnet:?xt=urn:btih:HASH
