### ISSUE TITLE
what about Poster/image of Sites torrents?

### ISSUE THREAD

**Issue by norm-git** [danimart1991/jackett2telegram#6]
I've only seen Poster on the CineCalidad site. but not in the others. It can be fixed?

**Comment by danimart1991** [comment]
Hi @norm-git.

Jackett2Telegram only shows the data that Jackett sends though RSS. The indexer must be defined in Jackett with Posters. Please open an issue in the [Jackett Repository](https://github.com/Jackett/Jackett/issues).
