### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by comassky** [danimart1991/jackett2telegram#7]
Hi,

First, thanks four your work ;)

My container crashes at launch.

My docker-compose :

```
 telegram:
     image: danimart1991/jackett2telegram
     container_name: Jackett-Telegram
     environment:
       - DELAY=60
       - TOKEN={telegram_bot_token}
       - CHATID={telegram_bot_chatid}
       - LOG_LEVEL=debug

```

My .env 

```
telegram_bot_token=5090<JOHNDOE>:AF<JOHNDOE>lS_GlK4
telegram_bot_chatid=-12345676
```

Error on starting : 

```
  File "jackett2telegram.py", line 539, in <module>
    main()
  File "jackett2telegram.py", line 500, in main
    updater = Updater(token=token, use_context=True)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py", line 290, in __init__
    else arbitrary_callback_data
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/extbot.py", line 103, in __init__
    private_key_password=private_key_password,
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 191, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 351, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
```

But when i use the Telegram API, it's ok 👍

![image](https://user-images.githubusercontent.com/48486646/147823024-cdbffc2e-2f85-45f0-b966-ca47b947ca5f.png)

**Comment by danimart1991** [comment]
Hi @comassky.

I think your `docker-compose.yml` file is not ok. You must use `env_file` to use the `.env` and not declare the enviroment variables in the compose file. Something like this:

```yaml
version: "2"

services:
  telegram:
    image: danimart1991/jackett2telegram
    container_name: Jackett-Telegram
    hostname: jackett2telegram
    env_file:
      - ./.env
```

**Comment by comassky** [comment]
Thanks @danimart1991 

Docker-compose uses by default the .env file or docker-compose.ini if it is present.

I have added the option, the error is still present.

```
telegram:
     image: danimart1991/jackett2telegram
     container_name: Jackett-Telegram
     environment:
       - DELAY=60
       - TOKEN={telegram_bot_token}
       - CHATID={telegram_bot_chatid}
       - LOG_LEVEL=debug
     env_file:
       - ./.env

```

Same .env file

```
Traceback (most recent call last):
  File "jackett2telegram.py", line 539, in <module>
    main()
  File "jackett2telegram.py", line 500, in main
    updater = Updater(token=token, use_context=True)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/updater.py", line 290, in __init__
    else arbitrary_callback_data
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/extbot.py", line 103, in __init__
    private_key_password=private_key_password,
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 191, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 351, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token

```

**Comment by danimart1991** [comment]
Hi again.

You are right. The `env_file` is not necessary. Indeed, the `enviroment` property and all its content must be removed from compose file and moved to `.env`.

**Comment by comassky** [comment]
@danimart1991 

I don't really understand.

The .env file contains the key=value variables that can be used in the docker-compose.

The .env does not replace the environments tag, it completes it.

I use this mechanism for all my other containers (about 30)

**Comment by comassky** [comment]
MY BAD

I forgot to add the $ symbol before the variables!

Sorry again, there was no bug!

Solution :

```
telegram:
     image: danimart1991/jackett2telegram
     container_name: Jackett-Telegram
     environment:
       - DELAY=60
       - TOKEN=${telegram_bot_token}
       - CHATID=${telegram_bot_chatid}
       - LOG_LEVEL=debug

```

**Comment by danimart1991** [comment]
Yes @comassky. 

But the `environment` field rules against the `.env`. So if you declare `TOKEN={telegram_bot_token}` in the compose file and `TOKEN=1234` in the `.env` file. TOKEN goes to have {telegram_bot_token} as value.

**Edit: I see your last message.**

My bad here maybe is use `{telegram_bot_token}` in the documentation instead maybe something like `<YourTelegramBotToken>` 🤔

**Comment by comassky** [comment]
@danimart1991 

I think your documentation is OK.

It's my conversion from docker-run/start to docker-compose that is messed up, with the environment variables forgotten.

By the way, maybe can you add an example of docker-compose in the readme (i can give you mine) ?
